---

- hosts: all
  become: true
  pre_tasks:

  - name: Ubuntu Update
    tags: always
    apt:
      update_cache: yes
      upgrade: dist

- hosts: Act_14
  become: true
  roles:
    - role: Keystone
    - role: Glance
    - role: Nova
