- name: install MariaDB
  apt:
    name: mariadb-server
    state: latest
    update_cache: yes

- name: Install Keystone
  apt:
    name: keystone
    state: latest
    update_cache: yes

- name: Install apache2
  apt:
    name: apache2
    state: latest
    update_cache: yes

- name: Restart apache2
  ansible.builtin.service:
   name: apache2
   state: restarted
