- name: Install MariaDB
  apt:
    name: mariadb-server
    state: latest

- name: Install Glance
  apt:
    name: glance
    state: latest

- name: Restart Glance
  ansible.builtin.service:
   name: glance-api
   state: restarted

